config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
  get "tasks", to: "tasks#index"
  get "tasks/new", to: "tasks#new"
  post "tasks", to: "tasks#create"
  get "tasks/:id", to: "tasks#show", as: :task
  get "tasks/:id/edit", to: "tasks#edit", as: :task_edit
  patch "tasks/:id", to: "tasks#update"
  delete "tasks/:id", to: "tasks#destroy", as: :task_delete
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    task = Task.new(task_params)
    task.save
    redirect_to task_path(task)
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @task.update(task_params)
    redirect_to task_path(@task)
  end

def destroy
  @task = Task.find(params[:id])
  @task.destroy
  redirect_to tasks_path, status: :see_other
end

  private

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Rails Task Manager" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.1.2/css/all.css">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
   </head>
   
  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<div class="container">
<h1>Edit <%= @task.title %></h1>

<%= form_with model: @task do |f| %>
  <%= f.label :title, class: "label" %>
  <%= f.text_field :title, class: "input-field" %>
  <%= f.label :details, class: "label" %>
  <%= f.text_field :details, class: "input-field" %>
  <%= f.label :completed, class: "label" %>
  <%= f.text_field :completed, class: "input-field" %>
  <%= f.submit class: "button" %>
<% end %>
</div>

app/views/tasks/index.html.erb
<div class="task-list">

<h1>All tasks</h1>

  <ul>
    <% @tasks.each do |task| %>
      <li><%= link_to task.title, task_path(task) %></li>
    <% end %>
  </ul>
<%= link_to'create new task', tasks_new_path, class: 'create-task-button' %>
</div>

app/views/tasks/new.html.erb
<div class="container">
<h1>Create a new task</h1>

<%= form_with model: @task do |f| %>
  <%= f.label :title, class: "label" %>
  <%= f.text_field :title, class: "input-field" %>
  <%= f.label :details, class: "label" %>
  <%= f.text_field :details, class: "input-field" %>
  <%= f.label :completed, class: "label" %>
  <%= f.number_field :completed, class: "input-field" %>
  <%= f.submit class: "button" %>
<% end %>
</div>

app/views/tasks/show.html.erb
<div class="task-details">
  <h1>Task <%= @task.title %></h1>
  <p>Details: <%= @task.details %></p>
  <p>Completed: <%= @task.completed %></p>
  <div class="actions">
    <%= link_to 'Back to all tasks', tasks_path %>
    <%= link_to 'Update task', task_edit_path(@task) %>
    <%= link_to 'Delete', task_delete_path(@task), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, class: 'delete' %>
  </div>
</div>